# default configuration
baseURL = "http://examplesite.com"
languageCode = "pt-br"
summaryLength = "10"
theme = "kross-hugo"
title = "PET Produção | UFC"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "sobre"
name = "Nossa história"
weight = 2

[[menu.main]]
URL = "projetos"
name = "Projetos"
weight = 3

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4

[[menu.main]]
URL = "time"
name = "Nosso time"
weight = 5

[[menu.main]]
URL = "curso"
name = "O curso"
weight = 6

[[menu.main]]
URL = "contato"
name = "Contato"
weight = 7

# default parameters
[params]
home = "Home"
logo = "images/logo-pet.png"
# theme color
theme_color = "#08829b" 
# contact info
phone = "+880 2544 658 256"
email = "steve.fruits@email.com"
address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "PET Produção"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "https://pt-br.facebook.com/petprod.ufc/"
icon = "ti-facebook"

[[params.social]]
URL = "https://www.instagram.com/petproducaoufc/"
icon = "ti-instagram"

[[params.social]]
URL = "#"
icon = "ti-dribbble"

[[params.social]]
URL = "#"
icon = "ti-twitter-alt"